# Generated by Django 4.1.3 on 2022-11-16 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainelement',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='kilimodata',
            name='referenceperiod',
        ),
        migrations.AddField(
            model_name='kilimodata',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.domain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='domainelement',
            name='domainelement',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='elementitem',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='flags',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='itemspecify',
            name='itemCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.itemcategory'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.county'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='datasource',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='domainelement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.domainelement'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='doneby',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.subsector'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='validated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
