# Generated by Django 4.1.3 on 2022-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0002_remove_domainelement_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilimodata',
            name='refperiod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
